services:
  app:
    command: ["dockerize", "-wait", "tcp://db:3306", "-timeout", "5m", "air", "-c", ".air.toml"]
    environment:
      DB: mysql
      DB_USERNAME: root
      DB_PASSWORD: pass
      DB_HOSTNAME: db
      DB_PORT: 3306
      DB_DATABASE: genorm
  db:
    image: mariadb:10.8.2
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: genorm
